### PR TITLE
coreutils and gnulib compilation scripts

### LINKED ISSUE #15: Add coreutils build scripts

### LINKED ISSUE #24: coreutils fails to build for WASI / wasm32 because several gnulib stdio files hard-error
I’m trying to compile coreutils for a WASI target using clang with --target=wasm32-unknown-wasi.
The build gets pretty far, but it always fails inside gnulib’s stdio helpers. Files like:
lib/fseterr, lib/freadahead.c, lib/freadptr.c, lib/freadseek.c, lib/fseeko.c.

They all got the same error:
#error "Please port gnulib XXX.c to your platform!"

### LINKED ISSUE #26: Missing arg-nonnull.h Causes _GL_ARG_NONNULL Errors in argv-iter.h
Building coreutils for WASI fails because gnulib’s _GL_ARG_NONNULL annotations expand incorrectly when arg-nonnull.h is missing. In argv-iter.h, these macros turn into stray tokens, and the compiler reports “expected function body after function declarator.” The build cannot proceed without a proper stub or generated header.

### PR DESCRIPTION
**Pull request by rennergade**
Closes #15 
Closes #24 
Closes #26 

## Changes

- Add a dedicated **coreutils WASI build script** and wire it into the top-level Makefile
- Add a **gnulib WASI build script** to produce a minimal static `libgnu.a` for `wasm32-wasi`
- Disable coreutils **mountlist detection** to avoid fatal configure errors on WASI
- Convert several gnulib hard `#error` paths into safe fallbacks:
  - `freadahead.c`, `freadptr.c`, `freadseek.c`, `fseeko.c`
- Replace gnulib’s Win32-oriented `sigaction` implementation with a **minimal WASI stub**
- Force **static, non-shared builds** to avoid `wasm-ld` incompatibilities
- Add a missing `#include <stdlib.h>` in a coreutils source file exposed by the WASI toolchain

Testing:

I successfuly ran the `mkdir` binary. I also tested `ls` but it fails due to: https://github.com/Lind-Project/lind-wasm/issues/662

### CODE REVIEW

File: coreutils/compile_coreutils.sh [hunk 1]
```diff
@@ -0,0 +1,481 @@
...
+#   - Stage produced wasm binaries even if some targets fail to link
+#   - wasm-opt + wasmtime compile (best-effort) on staged binaries
+###############################################################################
+
+SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
+APPS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
+COREUTILS_ROOT="$APPS_ROOT/coreutils"
+
+APPS_BUILD="$APPS_ROOT/build"
+MERGED_SYSROOT="$APPS_BUILD/sysroot_merged"
```
Comment (Yaxuan-w) [inline coreutils/compile_coreutils.sh]: Is the merged_sysroot same as regular sysroot?

Comment (rennergade) [reply coreutils/compile_coreutils.sh]: Merged sysroot is sysroot + any compiled libraries

**Review by m-hemmings — APPROVED** [review]
Looks good to me. The `gnulib`/`sysroot` wiring is clean, and the compilation approach feels pragmatic and well-thought-out.

File: coreutils/compile_coreutils.sh [hunk 2]
```diff
@@ -0,0 +1,481 @@
...
+}
+
+# ----------------------------------------------------------------------
+# 6) Configure + build (best-effort)
+# ----------------------------------------------------------------------
+patch_mountlist_fatal
+patch_gnulib_slow_but_no_hacks
+
+HOST_TRIPLET="${HOST_TRIPLET:-wasm32-unknown-linux-gnu}"
+BUILD_TRIPLET="${BUILD_TRIPLET:-$(./config.guess 2>/dev/null || echo x86_64-unknown-linux-gnu)}"
```
Comment (vidyalakshmir) [inline coreutils/compile_coreutils.sh]: The Host is the environment we are doing the build
Build is the environment that the compiled binaries are run.
Is that correct?

So wondering why we have it this way?

**Comment by rennergade** [comment]
> Looks good. I had some questions which I have posted.
> 
> Also, can you also add if any test was run to test the build? Thanks!



> Looks good. I had some questions which I have posted.
> 
> Also, can you also add if any test was run to test the build? Thanks!

I just ran a few of the binaries we dont have any testing setup yet

**Comment by vidyalakshmir** [comment]
Mentioning the binaries tested in the description might help us later while testing. Thanks

File: coreutils/compile_coreutils.sh [hunk 3]
```diff
@@ -0,0 +1,481 @@
...
+
+# ----------------------------------------------------------------------
+# 2) WASM toolchain flags (match bash style)
+#    NOTE: configure wants C99+ for some probes; use gnu99 here.
+# ----------------------------------------------------------------------
+CC_WASM="$CLANG --target=wasm32-unknown-wasi --sysroot=$MERGED_SYSROOT -pthread"
+
+CFLAGS_WASM=(
+  -O2 -g -std=gnu99 -pthread
+  -DHAVE_STRSIGNAL=1 -DHAVE_MKTIME=1
```
[the remark this answers is not in the document]
Comment (rennergade) [reply coreutils/compile_coreutils.sh]: these are needed to bypass some checks in configure

File: coreutils/compile_coreutils.sh (hunk 2 above)
Comment (rennergade) [reply coreutils/compile_coreutils.sh]: this is also configure vs the actual build
