### PR TITLE
Fix bash build output path to match standardized build layout

### LINKED ISSUE #125: Standardize the destination build folder for bash
Please ensure the following are done for each app:

1. There should be a 'target' in the main Makefile that would call all the scripts required for the build of each app as well as invoke any other. For eg: make bash

2. Once the build process is completed, the files produced by the app (binaries, configuration files, log files etc) should be copied to a folder ~/lind-wasm-app/build/$appname. In many cases, this can be done using make install DESTDIR=

For bash it will be `lind-wasm-apps/build/bash/bin/bash` and any other config or related files required by bash to run.

Refer to #124 for more details.

### PR DESCRIPTION
**Pull request by thisisadi**
Closes #125 

Fixes the bash build artifact path to match the standardized layout.

- Artifacts are now placed in:
`build/bash/bin/`
- Only `.cwasm` binary is copied to `build/bash/bin`.

- Set the default ARTIFACT_MODE flag to full 
- The build script fails in the following cases:
   - When ARTIFACT_MODE=fast returns error since .cwasm binary is not created
   - If wasm-opt is not found or if wasm-opt does not produce .opt.wasm binaries
   - If lind_boot does not exist or if it does not produce .cwasm files

- Added the flag `--fpcast-emu` for `wasm-opt` to remove indirect pointer cast mismatch error with tests.

### CODE REVIEW

File: bash/compile_bash.sh [hunk 1]
```diff
@@ -477,35 +476,32 @@ fi
...
-    echo "[bash] generating cwasm via lind-boot --precompile..."
-    if "$LIND_BOOT" --precompile "$BASH_OUT_DIR/bash.opt.wasm"; then
-      OPT_CWASM="$BASH_OUT_DIR/bash.opt.cwasm"
-      CLEAN_CWASM="$BASH_OUT_DIR/bash.cwasm"
-      if [[ -f "$OPT_CWASM" ]]; then
-        mv "$OPT_CWASM" "$CLEAN_CWASM"
+if [[ -x "$LIND_BOOT" ]]; then
+   echo "[bash] generating cwasm via lind-boot --precompile..."
+   if "$LIND_BOOT" --precompile "$BASH_WASM"; then
+      if [[ -f "$BASH_CWASM" ]]; then
```
Comment (m-hemmings) [inline bash/compile_bash.sh]: If lind-boot succeeds but "$BASH_CWASM" is still missing, this branch falls through and the build still reports success. Since this change is meant to require .cwasm output, should we add an else here that exits nonzero when the file was not created?
